task1 complete
Alphonnse/yaxkcdro pull request #2
Opened 2024-03-26 09:23 UTC by Alphonnse

snowball не всегда хорошо обрабатывает слова в предложении, но и сама либа не дает особо возможностей поработать с этим, поэтому стемминг не всегда может быть идеальным. Это можно посмотреть на примере 3 тесткейса TestStemSentence.

Так как snowball сам не удаляет дубликаты слов из предложения, я написала для этого функцию сам.
Решил использовать []string для хранения результирующего предложения, так как конкатенация стрингов обходится очень дорого по памяти (30 операций алокации против 10 на примере предложения из бенчмарка). 
Вот только при таком подходе при выводе приходится линейно пройти через для вывода. Хотел бы услышать советов от вас по этому поводу.

Для очистки предложения от стоп слов использовал эту библиотеку
https://github.com/bbalet/stopwords

Так же не стал создавать директорию bin внутри проекта для зависимостей, так как тут нет необходимости, мне кажется

2024-03-26 10:27 UTC, vbelogrudov commented
привет, []string на выходе - отличный вариант, мы его дальше будем использовать в других заданиях. То есть цель на сейчас - получить именно список ключей. Вывод на консоль не делает конкатенацию, просто пробегает по байтам слов.
bin на данном этапе не нужен.

2024-03-26 10:38 UTC, vbelogrudov requested changes
все отлично, есть пара мелочей в предыдущих комментариях и основная проблема в следующем тесте:

➜  yaxkcdro git:(task1) ./myapp -s "I'll follow followers xkcd"
follow followers xkcd %    

нам бы здесь xkcd и follow оставить

2024-03-26 10:38 UTC, vbelogrudov commented on Makefile
> +	go get -u github.com/bbalet/stopwords
как альтернатива, можно сделать go mod tidy - оно само все затянет

2024-03-26 10:38 UTC, vbelogrudov commented on Makefile
> +	go test -bench=. -benchmem -benchtime=10s -count=5
:+1:

2024-03-26 10:38 UTC, vbelogrudov commented on main.go
> +func stemSentence(str string) []string {
в будущем мы будем использовать подобную функцию много раз, желательно загружать stop слова один раз и, например, передавать сюда их слайсом вторым аргументом

2024-03-26 10:38 UTC, vbelogrudov commented on main.go
> +	for _, word := range strings.Split(str, " ") {
вместо Split() лучше использовать Fields() - она учитывает все пробельные варианты

2024-03-26 13:58 UTC, Alphonnse commented
➜ yaxkcdro git:(task1) ./myapp -s "I'll follow followers xkcd"
follow followers xkcd %

нам бы здесь xkcd и follow оставить

Тут же дело в том, что библиотека слово follows обрабатывает по своему, а у библиотеки я не увидел каких-то возможностей повлиять на обработку

пока что мне приходит идея сравнивать все слова между собой и исходя из результатов отбрасывать схожие, но мне почему-то кажется, что это можно решить как то более оптимально

я был бы рад советам)

2024-03-26 14:18 UTC, vbelogrudov requested changes
нужно разбить строку перед стеммингом

2024-03-26 14:18 UTC, vbelogrudov commented on main.go
> +	stemmed, _ := snowball.Stem(strWithoutStopwords, "english", true)
snowball.Stem работает с отдельными словами, то есть надо строчку разбить. https://github.com/kljensen/snowball/blob/master/snowball.go#L20

2024-03-27 11:04 UTC, Alphonnse commented
Проблему с многократной загрузкой stop слов решил тем, чтобы загрузить в отдельной функции из main, так как библиотека только передачу пути и загружает сам.

Поменял обработку ключей через os на flag, чтобы в будущем было проще контролировать, если их станет больше.

Добавил обработку ошибок.
Поменял strings.Split() на strings.Fields()

Совместил стемминг слов и отбрасывание повторяющихся слов в одну линейную функцию, мне кажется так красивее (результат бенчмарка будет примерно одинаковый с двумя проходами).

2024-03-27 13:35 UTC, vbelogrudov approved these changes
все отлично работает!

2024-03-27 13:36 UTC, vbelogrudov commented
можно мержить :)

2024-03-27 15:00 UTC, merged